### ISSUE TITLE
api document page error

### ISSUE THREAD

**Issue by wshhz** [input-output-hk/cardano-rest#37]
explorer-api: https://input-output-hk.github.io/cardano-rest/explorer-api/
submit-api: https://input-output-hk.github.io/cardano-rest/submit-api/

Unable to open the api document page, the following is the error message:
```
Something went wrong...
Error downloading https://raw.githubusercontent.com/input-output-hk/cardano-rest/master/explorer-api/swagger.yaml Failed to fetch
Stack trace
Error: Error downloading https://raw.githubusercontent.com/input-output-hk/cardano-rest/master/explorer-api/swagger.yaml 
Failed to fetch
    at https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.20/bundles/redoc.standalone.js:49:5419
    at https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.20/bundles/redoc.standalone.js:108:36105

TypeError: Failed to fetch

ReDoc Version: 2.0.0-rc.20
Commit: fd581261
```

**Comment by rhyslbw** [comment]
Seems to be resolved now
